<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="2" parallel="tests" name="Failed suite [Parallel Test Suite]">
  <test thread-count="2" parallel="tests" name="Test_2(failed)">
    <classes>
      <class name="Test.LoginTest">
        <methods>
          <include name="tearDown"/>
          <include name="loginWithValidUsers" invocation-numbers="0"/>
          <include name="loginWithLockedOutUser"/>
          <include name="loginAndLogoutWithCorrectUsernameAndPassword"/>
          <include name="setUp"/>
          <include name="pageSetUp"/>
        </methods>
      </class> <!-- Test.LoginTest -->
    </classes>
  </test> <!-- Test_2(failed) -->
  <test thread-count="2" parallel="tests" name="Test_1(failed)">
    <classes>
      <class name="Test.LoginTest">
        <methods>
          <include name="tearDown"/>
          <include name="loginWithValidUsers" invocation-numbers="0"/>
          <include name="setUp"/>
          <include name="pageSetUp"/>
        </methods>
      </class> <!-- Test.LoginTest -->
    </classes>
  </test> <!-- Test_1(failed) -->
</suite> <!-- Failed suite [Parallel Test Suite] -->
